[package]
name = "rustling-ontology-values"
version = "0.17.2"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
failure = "0.1.1"
regex = "0.2"
rustling = { git="https://github.com/snipsco/rustling", tag="0.9.0" }
rustling-ontology-moment = { path="../moment"}