[package]
name = "rustling-ontology-values"
version = "0.18.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
log = "0.4"
failure = "0.1"
regex = "1.0"
rustling = { git="https://github.com/snipsco/rustling", tag="0.9.0" }
rustling-ontology-moment = { path="../moment"}
